export const ErrorCodes = {
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    
    BROWSER_SEND_ERROR: "BROWSER_SEND_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    VALIDATION: "VALIDATION",
    NOT_FOUND: "NOT_FOUND",
    PATCH_VERSION_CONFLICT: "PATCH_VERSION_CONFLICT",
    USERNAME_EXISTS: "USERNAME_EXISTS",
    ALREADY_REGISTERED: "ALREADY_REGISTERED",
    INVALID_USERNAME_PASSWORD: "INVALID_USERNAME_PASSWORD",
    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    USER_OLD_PASSWORD_NOT_MATCH: "USER_OLD_PASSWORD_NOT_MATCH",
    DISCONNECTED: "DISCONNECTED",
    TIMEOUT: "TIMEOUT",
    INVALID_STATE: "INVALID_STATE",
} as const;

export type ErrorCode = keyof typeof ErrorCodes;
