export const ErrorCodes = {
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    
    BROWSER_SEND_ERROR: "BROWSER_SEND_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    VALIDATION: "VALIDATION",
    NOT_FOUND: "NOT_FOUND",
    PATCH_VERSION_CONFLICT: "PATCH_VERSION_CONFLICT",
    USERNAME_EXISTS: "USERNAME_EXISTS",
    ALREADY_REGISTERED: "ALREADY_REGISTERED",
    INVALID_USERNAME_PASSWORD: "INVALID_USERNAME_PASSWORD",
    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    USER_OLD_PASSWORD_NOT_MATCH: "USER_OLD_PASSWORD_NOT_MATCH",
    DISCONNECTED: "DISCONNECTED",
    TIMEOUT: "TIMEOUT",
    INVALID_STATE: "INVALID_STATE",
    FILE_TOO_LARGE: "FILE_TOO_LARGE",
    NO_FILES_UPLOADED: "NO_FILES_UPLOADED",
    ONLY_SINGLE_FILE_ALLOWED: "ONLY_SINGLE_FILE_ALLOWED",
    INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
    MISSING_BLUEPRINT_JSON: "MISSING_BLUEPRINT_JSON",
    BLUEPRINT_JSON_INVALID: "BLUEPRINT_JSON_INVALID",
    BLUEPRINT_JSON_VALIDATION_FAILED: "BLUEPRINT_JSON_VALIDATION_FAILED",
    ACTIVE_BLUEPRINT_DELETE_FORBIDDEN: "ACTIVE_BLUEPRINT_DELETE_FORBIDDEN",
    BLUEPRINT_ACTIVATION_FAILED: "BLUEPRINT_ACTIVATION_FAILED",
    BLUEPRINT_DEACTIVATION_FAILED: "BLUEPRINT_DEACTIVATION_FAILED",
    INVALID_RESOURCE_COMMAND: "INVALID_RESOURCE_COMMAND",
    INVALID_RESOURCE_TYPE: "INVALID_RESOURCE_TYPE",
    RESOURCE_NOT_ADDRESSABLE: "RESOURCE_NOT_ADDRESSABLE",
    APP_ENTRY_NOT_CONFIGURED: "APP_ENTRY_NOT_CONFIGURED",
    SYSTEM_BUSY: "SYSTEM_BUSY",
    // Add more error codes as needed
} as const;

export const ErrorMessages: Record<ErrorCode, string> = {
    INTERNAL_SERVER_ERROR: "Something went wrong on our end. Please try again later.",
    BROWSER_SEND_ERROR: "An error occurred while sending data to the server. Please try again.",
    UNAUTHORIZED: "You are not authorized to perform this action. Please log in and try again.",
    FORBIDDEN: "You do not have the necessary permissions to access this resource.",
    VALIDATION: "One or more fields contain invalid data. Please check and try again.",
    NOT_FOUND: "The requested resource could not be found.",
    USERNAME_EXISTS: "The username is already in use. Please choose a different one.",
    ALREADY_REGISTERED: "This account is already registered. Please log in.",
    INVALID_USERNAME_PASSWORD: "The username or password you entered is incorrect. Please try again.",
    INVALID_REFRESH_TOKEN: "Your session has expired or is invalid. Please log in again.",
    USER_NOT_FOUND: "The specified user could not be found.",
    USER_OLD_PASSWORD_NOT_MATCH: "The old password you entered is incorrect.",
    RESOURCE_NOT_FOUND: "The requested resource could not be found.",
    PATCH_VERSION_CONFLICT: "Version conflict detected.",
    DISCONNECTED: "You have been disconnected from the server. Please try again later.",
    TIMEOUT: "The request timed out. Please check your connection and try again.",
    INVALID_STATE: "The application is in an invalid state. Please refresh the page.",
    FILE_TOO_LARGE: "The uploaded file is too large.",
    NO_FILES_UPLOADED: "No files were uploaded.",
    ONLY_SINGLE_FILE_ALLOWED: "Only a single file is allowed for this upload.",
    INVALID_FILE_TYPE: "The uploaded file type is not supported.",
    MISSING_BLUEPRINT_JSON: "The blueprint upload is missing the required blueprint.json file.",
    BLUEPRINT_JSON_INVALID: "The blueprint.json file is invalid or malformed.",
    BLUEPRINT_JSON_VALIDATION_FAILED: "The blueprint.json file failed validation against the required schema.",
    ACTIVE_BLUEPRINT_DELETE_FORBIDDEN: "Cannot delete an active blueprint version.",
    BLUEPRINT_ACTIVATION_FAILED: "Failed to activate the blueprint due to an internal error.",
    BLUEPRINT_DEACTIVATION_FAILED: "Failed to deactivate the blueprint due to an internal error.",
    INVALID_RESOURCE_COMMAND: "The command sent to the resource is invalid.",
    INVALID_RESOURCE_TYPE: "The resource type does not support this command.",
    RESOURCE_NOT_ADDRESSABLE: "The resource is not addressable.",
    APP_ENTRY_NOT_CONFIGURED: "The application entry point is not configured.",
    SYSTEM_BUSY: "The system is currently busy processing another command. Please try again later.",
    // Add more error mappings as needed
};
export type ErrorCode = keyof typeof ErrorCodes;
