export const basePlatformConfig = {
    tags: [
        { name: "header-menu" },
        { name: "profile-icon" },
    ],
    pages: [
        { identifier: "login", name: "Login" },
        { identifier: "register", name: "Register" },
        { identifier: "register-thank-you", name: "RegisterThankYou" },
        { identifier: "my-profile", name: "My Profile" },
        { identifier: "my-settings", name: "My Settings" },
        { identifier: "start-page", name: "Start Page" },
        { identifier: "control-panel", name: "Control Panel" },
    ],
    pageApps: [
        { page: "login", internalComponent: "LoginPage", order: 1 },
        { page: "register", internalComponent: "RegisterPage", order: 1 },
        { page: "register-thank-you", internalComponent: "RegistrationThankYouPage", order: 1 },
        { page: "my-profile", internalComponent: "MyProfilePage", order: 1, roles: ["user"] },
        { page: "my-settings", internalComponent: "MySettingsPage", order: 1, roles: ["user"] },
        { page: "start-page", internalComponent: "StartPage", order: 1, roles: ["user"] },
        { page: "control-panel", internalComponent: "ControlPanelPage", order: 1, roles: ["admin"] },
    ],
    routes: [
        { identifier: "login", routePattern: "/login", link: "/login", page: "login", accessType: "unauthenticated" },
        { identifier: "register", routePattern: "/register", link: "/register", page: "register", accessType: "unauthenticated" },
        { identifier: "register-thank-you", routePattern: "/register-thank-you", link: "/register-thank-you", page: "register-thank-you", accessType: "unauthenticated" },
        { identifier: "my-profile", routePattern: "/my-profile", link: "/my-profile", page: "my-profile", accessType: "authenticated" },
        { identifier: "my-settings", routePattern: "/my-settings", link: "/my-settings", page: "my-settings", accessType: "authenticated" },
        { identifier: "start-page", routePattern: "/start", link: "/start", page: "start-page", accessType: "authenticated" },
        { identifier: "control-panel-root", routePattern: "/control-panel/*", link: "/control-panel/", page: "control-panel", accessType: "role-based", roles: ["admin"] },
        { identifier: "unauth-default", routePattern: "*", accessType: "unauthenticated", config: { redirect: "/login" } },
        { identifier: "auth-default", routePattern: "*", accessType: "authenticated", config: { redirect: "/" } },
    ],
    routeTags: [
        { route: "auth-root", tag: "header-menu", routeOrder: 1 },
        { route: "my-settings", tag: "profile-icon", routeOrder: 1 },
        { route: "my-profile", tag: "profile-icon", routeOrder: 2 },
        { route: "control-panel-root", tag: "profile-icon", routeOrder: 3 },
    ],
} as const;
