import type { FactoryMapping } from "./factory-mapping";
import type { ParsedDevice, UHNProperty } from "./types";
import { capitalize, deviceToVarPrefix } from "./naming";

type DevicesByKind = Map<string, Set<string>>; // kind → device names

/**
 * Generates a zigbee factory TypeScript file for a specific edge.
 * Exports device type unions and factory wrapper functions.
 * Always regenerated (not author-edited).
 *
 * Kinds that are already mapped to a non-zigbee factory in the mapping
 * are skipped — only device type unions include all devices regardless.
 */
export function generateFactoryFile(devices: ParsedDevice[], edge: string, mapping: FactoryMapping): string {
    const zigbeeImport = `../factory/zigbee-factory-${edge}`;

    /** Returns true if this type.kind should get a factory in the zigbee file */
    function needsZigbeeFactory(uhnType: string, kind: string): boolean {
        const key = `${uhnType}.${kind}`;
        const ref = mapping[key];
        // Generate if unmapped (new kind) or mapped to this zigbee factory file
        return !ref || ref.import === zigbeeImport;
    }
    const lines: string[] = [];

    // Collect device names per resource type + kind
    const outputDevices: DevicesByKind = new Map();
    const inputDevices: DevicesByKind = new Map();
    const analogInputDevices: DevicesByKind = new Map();
    const analogOutputDevices: DevicesByKind = new Map();

    // Also collect all devices per broad type (for the union types)
    const allOutputDeviceNames = new Set<string>();
    const allInputDeviceNames = new Set<string>();
    const allAnalogInputDeviceNames = new Set<string>();
    const allAnalogOutputDeviceNames = new Set<string>();
    const allActionInputDeviceNames = new Set<string>();

    for (const device of devices) {
        for (const prop of device.properties) {
            switch (prop.uhnType) {
                case "digitalOutput": {
                    allOutputDeviceNames.add(device.friendlyName);
                    const kind = inferOutputKind(prop, device);
                    if (needsZigbeeFactory("digitalOutput", kind))
                        addToKindMap(outputDevices, kind, device.friendlyName);
                    break;
                }
                case "digitalInput": {
                    allInputDeviceNames.add(device.friendlyName);
                    const kind = inferInputKind(prop);
                    if (needsZigbeeFactory("digitalInput", kind))
                        addToKindMap(inputDevices, kind, device.friendlyName);
                    break;
                }
                case "analogInput": {
                    allAnalogInputDeviceNames.add(device.friendlyName);
                    const kind = mapAnalogInputKind(prop.pin, prop.unit);
                    if (needsZigbeeFactory("analogInput", kind))
                        addToKindMap(analogInputDevices, kind, device.friendlyName);
                    break;
                }
                case "analogOutput": {
                    allAnalogOutputDeviceNames.add(device.friendlyName);
                    const kind = mapAnalogOutputKind(prop.pin);
                    if (needsZigbeeFactory("analogOutput", kind))
                        addToKindMap(analogOutputDevices, kind, device.friendlyName);
                    break;
                }
                case "actionInput": {
                    allActionInputDeviceNames.add(device.friendlyName);
                    break;
                }
            }
        }
    }

    lines.push(`// Auto-generated by uhn-blueprint-tools z2m-import — DO NOT EDIT`);
    lines.push(`// Regenerated on every import run. Manual edits will be overwritten.`);
    lines.push(``);

    // Collect which base factories we need (only for kinds with zigbee factory functions)
    const usedFactories = new Set<string>();
    if (outputDevices.size > 0) usedFactories.add("digitalOutput");
    if (inputDevices.size > 0) usedFactories.add("digitalInput");
    if (analogInputDevices.size > 0) usedFactories.add("analogInput");
    if (analogOutputDevices.size > 0) usedFactories.add("analogOutput");

    // Collect which type imports we need
    const usedTypes = new Set<string>();
    if (outputDevices.size > 0) usedTypes.add("DigitalOutputResourceBase");
    if (inputDevices.size > 0) usedTypes.add("DigitalInputResourceBase");
    if (analogInputDevices.size > 0) usedTypes.add("AnalogInputResourceBase");
    if (analogOutputDevices.size > 0) usedTypes.add("AnalogOutputResourceBase");

    const imports = [...usedFactories, ...usedTypes].sort();
    lines.push(`import { ${imports.join(", ")} } from "@uhn/blueprint";`);
    lines.push(``);

    // Device type unions
    const edgeSuffix = capitalize(deviceToVarPrefix(edge));
    lines.push(`// Device type unions for ${edge} Zigbee devices`);
    lines.push(`export type ZigbeeDigitalOutputDevice${edgeSuffix} = ${formatUnion(allOutputDeviceNames)};`);
    lines.push(`export type ZigbeeDigitalInputDevice${edgeSuffix} = ${formatUnion(allInputDeviceNames)};`);
    lines.push(`export type ZigbeeAnalogInputDevice${edgeSuffix} = ${formatUnion(allAnalogInputDeviceNames)};`);
    lines.push(`export type ZigbeeAnalogOutputDevice${edgeSuffix} = ${formatUnion(allAnalogOutputDeviceNames)};`);
    lines.push(`export type ZigbeeActionInputDevice${edgeSuffix} = ${formatUnion(allActionInputDeviceNames)};`);
    lines.push(``);

    const edgeConst = `EDGE_${edge.toUpperCase().replace(/[^A-Z0-9]/g, "_")}_ZIGBEE`;
    lines.push(`export const ${edgeConst} = "${edge}" as const;`);
    lines.push(`type Edge = typeof ${edgeConst};`);
    lines.push(``);

    // Generate factory wrappers per output kind
    for (const [kind, deviceNames] of outputDevices) {
        const fnName = `zigbee${capitalize(kind)}`;
        const deviceUnion = formatUnion(deviceNames);
        lines.push(`export type ${capitalize(fnName)}Props = Omit<DigitalOutputResourceBase<"${kind}", Edge, ${deviceUnion}>, "type" | "outputKind">;`);
        lines.push(`export function ${fnName}(props: ${capitalize(fnName)}Props) {`);
        lines.push(`    return digitalOutput<"${kind}", Edge, ${deviceUnion}>({ ...props, outputKind: "${kind}" });`);
        lines.push(`}`);
        lines.push(``);
    }

    // Generate factory wrappers per input kind
    for (const [kind, deviceNames] of inputDevices) {
        const fnName = `zigbee${capitalize(kind)}Sensor`;
        const deviceUnion = formatUnion(deviceNames);
        lines.push(`export type ${capitalize(fnName)}Props = Omit<DigitalInputResourceBase<"${kind}", Edge, ${deviceUnion}>, "type" | "inputKind" | "inputType">;`);
        lines.push(`export function ${fnName}(props: ${capitalize(fnName)}Props) {`);
        lines.push(`    return digitalInput<"${kind}", Edge, ${deviceUnion}>({ ...props, inputKind: "${kind}", inputType: "push" });`);
        lines.push(`}`);
        lines.push(``);
    }

    // Generate factory wrappers per analog input kind
    for (const [kind, deviceNames] of analogInputDevices) {
        const fnName = `zigbee${capitalize(kind)}Sensor`;
        const deviceUnion = formatUnion(deviceNames);
        const extraProps = getAnalogInputDefaults(kind);
        lines.push(`export type ${capitalize(fnName)}Props = Omit<AnalogInputResourceBase<"${kind}", Edge, ${deviceUnion}>, "type" | "analogInputKind">;`);
        lines.push(`export function ${fnName}(props: ${capitalize(fnName)}Props) {`);
        lines.push(`    return analogInput<"${kind}", Edge, ${deviceUnion}>({ ${extraProps}...props, analogInputKind: "${kind}" });`);
        lines.push(`}`);
        lines.push(``);
    }

    // Generate factory wrappers per analog output kind
    for (const [kind, deviceNames] of analogOutputDevices) {
        const fnName = `zigbee${capitalize(kind)}`;
        const deviceUnion = formatUnion(deviceNames);
        lines.push(`export type ${capitalize(fnName)}Props = Omit<AnalogOutputResourceBase<"${kind}", Edge, ${deviceUnion}>, "type" | "analogOutputKind">;`);
        lines.push(`export function ${fnName}(props: ${capitalize(fnName)}Props) {`);
        lines.push(`    return analogOutput<"${kind}", Edge, ${deviceUnion}>({ ...props, analogOutputKind: "${kind}" });`);
        lines.push(`}`);
        lines.push(``);
    }

    // Generate per-device action union types (meta maps go in resource files — author-editable)


    return lines.join("\n");
}

function addToKindMap(map: DevicesByKind, kind: string, deviceName: string): void {
    if (!map.has(kind)) map.set(kind, new Set());
    map.get(kind)!.add(deviceName);
}

function formatUnion(names: Set<string>): string {
    if (names.size === 0) return "never";
    return [...names].sort().map(n => `"${n}"`).join(" | ");
}



function getAnalogInputDefaults(kind: string): string {
    switch (kind) {
        case "temperature": return `unit: "°C", decimalPrecision: 1, `;
        case "humidity": return `unit: "%", decimalPrecision: 1, `;
        case "battery": return `unit: "%", decimalPrecision: 0, `;
        case "power": return `unit: "W", decimalPrecision: 0, `;
        case "voltage": return `unit: "V", decimalPrecision: 0, `;
        case "current": return `unit: "A", decimalPrecision: 2, `;
        case "energy": return `unit: "kWh", `;
        default: return "";
    }
}

// Duplicated from resource-gen — keeping here to avoid circular dependency
function inferOutputKind(prop: UHNProperty, device: ParsedDevice): string {
    if (prop.pin !== "state") return "relay";
    const desc = (device.description ?? "").toLowerCase();
    const hasLightProps = device.properties.some(p =>
        p.pin === "brightness" || p.pin === "color_temp" || p.pin === "color"
    );
    if (hasLightProps) return "light";
    if (/\b(light|led|bulb|lamp)\b/.test(desc)) return "light";
    if (/\b(plug|outlet|socket)\b/.test(desc)) return "socket";
    if (/\b(relay)\b/.test(desc)) return "relay";
    if (/\b(switch)\b/.test(desc)) return "socket";
    return "socket";
}

function inferInputKind(prop: UHNProperty): string {
    const pin = prop.pin.toLowerCase();
    const desc = (prop.description ?? "").toLowerCase();
    if (pin === "occupancy" || /\bmotion\b/.test(desc) || /\bpresence\b/.test(desc)) return "pir";
    if (pin === "contact" || /\bdoor\b/.test(desc) || /\bwindow\b/.test(desc)) return "button";
    return "sensor";
}

function mapAnalogInputKind(pin: string, unit?: string): string {
    if (pin === "battery") return "battery";
    if (pin === "temperature" || unit === "°C") return "temperature";
    if (pin === "humidity" || unit === "%") return "humidity";
    if (pin === "power" || unit === "W") return "power";
    if (pin === "voltage" || unit === "V") return "voltage";
    if (pin === "current" || unit === "A") return "current";
    if (pin === "energy" || unit === "kWh") return "energy";
    return "sensor";
}

function mapAnalogOutputKind(pin: string): string {
    if (pin === "brightness") return "dimmer";
    if (pin === "color_temp") return "colorTemp";
    return "control";
}

function inferActionInputKind(device: ParsedDevice): string {
    const desc = (device.description ?? "").toLowerCase();
    if (/\b(remote|controller)\b/.test(desc)) return "remote";
    return "button";
}
