import type { ParsedDevice, UHNProperty } from "./types";
import { capitalize, deviceToVarPrefix } from "./naming";

type DevicesByKind = Map<string, Set<string>>; // kind → device names

/**
 * Generates a zigbee factory TypeScript file for a specific edge.
 * Exports device type unions and factory wrapper functions.
 * Always regenerated (not author-edited).
 */
export function generateFactoryFile(devices: ParsedDevice[], edge: string): string {
    const lines: string[] = [];

    // Collect device names per resource type + kind
    const outputDevices: DevicesByKind = new Map();
    const inputDevices: DevicesByKind = new Map();
    const analogInputDevices: DevicesByKind = new Map();
    const analogOutputDevices: DevicesByKind = new Map();

    // Also collect all devices per broad type (for the union types)
    const allOutputDeviceNames = new Set<string>();
    const allInputDeviceNames = new Set<string>();
    const allAnalogInputDeviceNames = new Set<string>();
    const allAnalogOutputDeviceNames = new Set<string>();

    for (const device of devices) {
        for (const prop of device.properties) {
            switch (prop.uhnType) {
                case "digitalOutput":
                    allOutputDeviceNames.add(device.friendlyName);
                    addToKindMap(outputDevices, inferOutputKind(prop, device), device.friendlyName);
                    break;
                case "digitalInput":
                    allInputDeviceNames.add(device.friendlyName);
                    addToKindMap(inputDevices, inferInputKind(prop), device.friendlyName);
                    break;
                case "analogInput":
                    allAnalogInputDeviceNames.add(device.friendlyName);
                    addToKindMap(analogInputDevices, mapAnalogInputKind(prop.pin, prop.unit), device.friendlyName);
                    break;
                case "analogOutput":
                    allAnalogOutputDeviceNames.add(device.friendlyName);
                    addToKindMap(analogOutputDevices, mapAnalogOutputKind(prop.pin), device.friendlyName);
                    break;
            }
        }
    }

    lines.push(`// Auto-generated by uhn-blueprint-tools z2m-import — DO NOT EDIT`);
    lines.push(`// Regenerated on every import run. Manual edits will be overwritten.`);
    lines.push(``);

    // Collect which base factories we need
    const usedFactories = new Set<string>();
    if (allOutputDeviceNames.size > 0) usedFactories.add("digitalOutput");
    if (allInputDeviceNames.size > 0) usedFactories.add("digitalInput");
    if (allAnalogInputDeviceNames.size > 0) usedFactories.add("analogInput");
    if (allAnalogOutputDeviceNames.size > 0) usedFactories.add("analogOutput");

    // Collect which type imports we need
    const usedTypes = new Set<string>();
    if (allOutputDeviceNames.size > 0) usedTypes.add("DigitalOutputResourceBase");
    if (allInputDeviceNames.size > 0) usedTypes.add("DigitalInputResourceBase");
    if (allAnalogInputDeviceNames.size > 0) usedTypes.add("AnalogInputResourceBase");
    if (allAnalogOutputDeviceNames.size > 0) usedTypes.add("AnalogOutputResourceBase");

    const imports = [...usedFactories, ...usedTypes].sort();
    lines.push(`import { ${imports.join(", ")} } from "@uhn/blueprint";`);
    lines.push(``);

    // Device type unions
    const edgeSuffix = capitalize(deviceToVarPrefix(edge));
    lines.push(`// Device type unions for ${edge} Zigbee devices`);
    lines.push(`export type ZigbeeDigitalOutputDevice${edgeSuffix} = ${formatUnion(allOutputDeviceNames)};`);
    lines.push(`export type ZigbeeDigitalInputDevice${edgeSuffix} = ${formatUnion(allInputDeviceNames)};`);
    lines.push(`export type ZigbeeAnalogInputDevice${edgeSuffix} = ${formatUnion(allAnalogInputDeviceNames)};`);
    lines.push(`export type ZigbeeAnalogOutputDevice${edgeSuffix} = ${formatUnion(allAnalogOutputDeviceNames)};`);
    lines.push(``);

    const edgeConst = `EDGE_${edge.toUpperCase().replace(/[^A-Z0-9]/g, "_")}_ZIGBEE`;
    lines.push(`export const ${edgeConst} = "${edge}" as const;`);
    lines.push(`type Edge = typeof ${edgeConst};`);
    lines.push(`type Pin = number | string;`);
    lines.push(``);

    // Generate factory wrappers per output kind
    for (const [kind, deviceNames] of outputDevices) {
        const fnName = `zigbee${capitalize(kind)}`;
        const deviceUnion = formatUnion(deviceNames);
        lines.push(`export type ${capitalize(fnName)}Props = Omit<DigitalOutputResourceBase<"${kind}", Edge, ${deviceUnion}, Pin>, "type" | "outputKind">;`);
        lines.push(`export function ${fnName}(props: ${capitalize(fnName)}Props) {`);
        lines.push(`    return digitalOutput<"${kind}", Edge, ${deviceUnion}, Pin>({ ...props, outputKind: "${kind}" });`);
        lines.push(`}`);
        lines.push(``);
    }

    // Generate factory wrappers per input kind
    for (const [kind, deviceNames] of inputDevices) {
        const fnName = `zigbee${capitalize(kind)}Sensor`;
        const deviceUnion = formatUnion(deviceNames);
        lines.push(`export type ${capitalize(fnName)}Props = Omit<DigitalInputResourceBase<"${kind}", Edge, ${deviceUnion}, Pin>, "type" | "inputKind" | "inputType">;`);
        lines.push(`export function ${fnName}(props: ${capitalize(fnName)}Props) {`);
        lines.push(`    return digitalInput<"${kind}", Edge, ${deviceUnion}, Pin>({ ...props, inputKind: "${kind}", inputType: "push" });`);
        lines.push(`}`);
        lines.push(``);
    }

    // Generate factory wrappers per analog input kind
    for (const [kind, deviceNames] of analogInputDevices) {
        const fnName = `zigbee${capitalize(kind)}Sensor`;
        const deviceUnion = formatUnion(deviceNames);
        const extraProps = getAnalogInputDefaults(kind);
        lines.push(`export type ${capitalize(fnName)}Props = Omit<AnalogInputResourceBase<"${kind}", Edge, ${deviceUnion}, Pin>, "type" | "analogInputKind">;`);
        lines.push(`export function ${fnName}(props: ${capitalize(fnName)}Props) {`);
        lines.push(`    return analogInput<"${kind}", Edge, ${deviceUnion}, Pin>({ ${extraProps}...props, analogInputKind: "${kind}" });`);
        lines.push(`}`);
        lines.push(``);
    }

    // Generate factory wrappers per analog output kind
    for (const [kind, deviceNames] of analogOutputDevices) {
        const fnName = `zigbee${capitalize(kind)}`;
        const deviceUnion = formatUnion(deviceNames);
        lines.push(`export type ${capitalize(fnName)}Props = Omit<AnalogOutputResourceBase<"${kind}", Edge, ${deviceUnion}, Pin>, "type" | "analogOutputKind">;`);
        lines.push(`export function ${fnName}(props: ${capitalize(fnName)}Props) {`);
        lines.push(`    return analogOutput<"${kind}", Edge, ${deviceUnion}, Pin>({ ...props, analogOutputKind: "${kind}" });`);
        lines.push(`}`);
        lines.push(``);
    }

    return lines.join("\n");
}

function addToKindMap(map: DevicesByKind, kind: string, deviceName: string): void {
    if (!map.has(kind)) map.set(kind, new Set());
    map.get(kind)!.add(deviceName);
}

function formatUnion(names: Set<string>): string {
    if (names.size === 0) return "never";
    return [...names].sort().map(n => `"${n}"`).join(" | ");
}



function getAnalogInputDefaults(kind: string): string {
    switch (kind) {
        case "temperature": return `unit: "°C", decimalPrecision: 1, `;
        case "humidity": return `unit: "%", decimalPrecision: 1, `;
        case "battery": return `unit: "%", decimalPrecision: 0, `;
        case "power": return `unit: "W", decimalPrecision: 0, `;
        case "voltage": return `unit: "V", decimalPrecision: 0, `;
        case "current": return `unit: "A", decimalPrecision: 2, `;
        case "energy": return `unit: "kWh", `;
        default: return "";
    }
}

// Duplicated from resource-gen — keeping here to avoid circular dependency
function inferOutputKind(prop: UHNProperty, device: ParsedDevice): string {
    if (prop.pin !== "state") return "relay";
    const desc = (device.description ?? "").toLowerCase();
    const hasLightProps = device.properties.some(p =>
        p.pin === "brightness" || p.pin === "color_temp" || p.pin === "color"
    );
    if (hasLightProps) return "light";
    if (/\b(light|led|bulb|lamp)\b/.test(desc)) return "light";
    if (/\b(plug|outlet|socket)\b/.test(desc)) return "socket";
    if (/\b(relay)\b/.test(desc)) return "relay";
    if (/\b(switch)\b/.test(desc)) return "socket";
    return "socket";
}

function inferInputKind(prop: UHNProperty): string {
    const pin = prop.pin.toLowerCase();
    const desc = (prop.description ?? "").toLowerCase();
    if (pin === "occupancy" || /\bmotion\b/.test(desc) || /\bpresence\b/.test(desc)) return "pir";
    if (pin === "contact" || /\bdoor\b/.test(desc) || /\bwindow\b/.test(desc)) return "button";
    return "sensor";
}

function mapAnalogInputKind(pin: string, unit?: string): string {
    if (pin === "battery") return "battery";
    if (pin === "temperature" || unit === "°C") return "temperature";
    if (pin === "humidity" || unit === "%") return "humidity";
    if (pin === "power" || unit === "W") return "power";
    if (pin === "voltage" || unit === "V") return "voltage";
    if (pin === "current" || unit === "A") return "current";
    if (pin === "energy" || unit === "kWh") return "energy";
    return "sensor";
}

function mapAnalogOutputKind(pin: string): string {
    if (pin === "brightness") return "dimmer";
    if (pin === "color_temp") return "colorTemp";
    return "control";
}
